# Generated by Django 2.2.2 on 2019-06-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0004_auto_20190608_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentattendance',
            name='students',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainattendance.Student'),
        ),
    ]
