# Generated by Django 2.2.2 on 2019-06-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0006_auto_20190609_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentattendance',
            name='students',
        ),
    ]
