# Generated by Django 2.2.2 on 2019-06-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0007_remove_currentattendance_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentattendance',
            name='students',
            field=models.ManyToManyField(related_name='students', to='mainattendance.Student'),
        ),
    ]
