# Generated by Django 2.2.2 on 2019-06-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0009_auto_20190610_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentattendance',
            options={'ordering': ('date', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='currentattendance',
            unique_together={('date', 'batch')},
        ),
    ]
