# Generated by Django 2.2.2 on 2019-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0010_auto_20190610_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
