# Generated by Django 2.2.2 on 2019-06-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0011_auto_20190610_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentattendance',
            options={},
        ),
    ]
