# Generated by Django 2.2.2 on 2019-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0012_auto_20190611_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('attendance', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
