# Generated by Django 2.2.2 on 2019-06-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0013_studentattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student_id', 'attendance')},
        ),
    ]
