# Generated by Django 2.2.2 on 2019-06-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0014_auto_20190613_0505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student_id', 'date')},
        ),
    ]
