# Generated by Django 2.2.2 on 2019-06-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0016_auto_20190613_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_date', models.DateField()),
            ],
        ),
    ]
