# Generated by Django 2.2.2 on 2019-06-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainattendance', '0018_auto_20190615_0455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
    ]
